#!/bin/bash


function show_idan(){
  echo  -e "\033[0;36m                    dddddddd                                   
  iiii              d::::::d                                   
 i::::i             d::::::d                                   
  iiii              d::::::d                                   
                    d:::::d                                    
iiiiiii     ddddddddd:::::d   aaaaaaaaaaaaa  nnnn  nnnnnnnn    
i:::::i   dd::::::::::::::d   a::::::::::::a n:::nn::::::::nn  
 i::::i  d::::::::::::::::d   aaaaaaaaa:::::an::::::::::::::nn 
 i::::i d:::::::ddddd:::::d            a::::ann:::::::::::::::n
 i::::i d::::::d    d:::::d     aaaaaaa:::::a  n:::::nnnn:::::n
 i::::i d:::::d     d:::::d   aa::::::::::::a  n::::n    n::::n
 i::::i d:::::d     d:::::d  a::::aaaa::::::a  n::::n    n::::n
 i::::i d:::::d     d:::::d a::::a    a:::::a  n::::n    n::::n
i::::::id::::::ddddd::::::dda::::a    a:::::a  n::::n    n::::n
i::::::i d:::::::::::::::::da:::::aaaa::::::a  n::::n    n::::n
i::::::i  d:::::::::ddd::::d a::::::::::aa:::a n::::n    n::::n
iiiiiiii   ddddddddd   ddddd  aaaaaaaaaa  aaaa nnnnnn    nnnnnn
"

printf "💻 Built by: \e]8;;http://twitter.com/aremu_smog\e\\Aremu Smog\e]8;;\e\\"
echo ""

}

SUPPORTED_PACKAGES=("npm" "yarn" "pnpm")

SELECTED_PACKAGE_MANAGER_FILE="/tmp/idan.dat"

# if there is no file, means no package manager selected
if [ ! -f "$SELECTED_PACKAGE_MANAGER_FILE" ]; then
    PACKAGE_MANAGER=""

# otherwise read the value from the file
else
    PACKAGE_MANAGER=$(cat "$SELECTED_PACKAGE_MANAGER_FILE")
fi

function check_installed_packages(){
COUNT_INSTALLED_PACKAGE_MANAGERS=0

echo ""
echo -e "\033[0;36m✅:Package in use | 🌟:Installed | ❌: Not Installed"
echo ""
echo "Supported Package Managers are:"
echo ""

for package in "${SUPPORTED_PACKAGES[@]}"; do
PACKAGE_MANAGER_CHECK=$(which $package)
PACKAGE_VERSION="n/a"
if [[ $PACKAGE_MANAGER_CHECK != "" ]]; then
IS_SUPPORTED=true
IS_SUPPORTED_ICON="🌟"
PACKAGE_VERSION=$($package -v)
if [[ "$PACKAGE_MANAGER" == "$package" ]]; then
IS_SUPPORTED_ICON="✅"
fi
else
IS_SUPPORTED_ICON="❌"
IS_SUPPORTED=false
fi
COUNT_INSTALLED_PACKAGE_MANAGERS=$COUNT_INSTALLED_PACKAGE_MANAGERS+1
echo "${IS_SUPPORTED_ICON} ${package} | ${PACKAGE_VERSION}"
done

if [[ COUNT_INSTALLED_PACKAGE_MANAGERS == 0 ]]; then
  echo "No node package manager installed on your machine"
  echo "Yarn: https://yarnpkg.com/"
  echo "NPM:  https://nodejs.org/en"
  echo "Pnpm: https://pnpm.io/"
fi
}


function set_package_manager(){
  echo "$1" > "$SELECTED_PACKAGE_MANAGER_FILE"
  PACKAGE_MANAGER=$1
  echo "🥳 idan will now use ${PACKAGE_MANAGER} as your package manager"
}

function handle_input(){
  if [[ $PACKAGE_MANAGER != "" ]]; then
    case $1 in
      obtain)
        $PACKAGE_MANAGER add $@
      ;;
      comot)
        $PACKAGE_MANAGER remove $@
      ;;
      *)
        $PACKAGE_MANAGER $@
        ;;
    esac
  else
  show_idan
  fi
}

case $1 in
  shadow)
    check_installed_packages
  ;;
  yarn | npm | pnpm)
    set_package_manager $1
  ;;
  gangan)
    show_idan
  ;;
  *)
    handle_input
  ;;
esac





